image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ""

services:
  - name: docker:dind
    alias: docker

stages:
    - build

before_script:
    - 

build:
    stage: build
    script:
        - |
          if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
            tag=""
            echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
          else
            tag=":$CI_COMMIT_REF_SLUG"
            echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
          fi
        - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
        - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
        - docker push "$CI_REGISTRY_IMAGE${tag}"
        - docker logout
        - docker login -u vfaergestad -p DOCKER_HUB_TOKEN 
        - docker push "vfaergestad/cyberchef:$tag"
    rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
