image: docker:latest

services:
  - name: docker:dind
    alias: docker

stages:
    - build

before_script:
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY

build:
    stage: build
    script:
        - |
          if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
            tag=""
            echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
          else
            tag=":$CI_COMMIT_REF_SLUG"
            echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
          fi
        - docker build -t "$CI_REGISTRY_IMAGE${tag}" .
        - docker push "$CI_REGISTRY_IMAGE${tag}"
    rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
