image: docker:latest

variables:
  DOCKER_TLS_CERTDIR: ""
  DOCKER_HUB_REGISTRY: "vfaergestad/cyberchef"

services:
  - name: docker:dind
    alias: docker

stages:
    - build

before_script:
    - unset DOCKER_HOST
    - docker login -u gitlab-ci-token -p $CI_JOB_TOKEN $CI_REGISTRY
    - docker login -u vfaergestad -p $DOCKER_HUB_TOKEN 

build:
    stage: build
    script:
        - unset DOCKER_HOST
        - |
          if [[ "$CI_COMMIT_BRANCH" == "$CI_DEFAULT_BRANCH" ]]; then
            tag=""
            echo "Running on default branch '$CI_DEFAULT_BRANCH': tag = 'latest'"
          else
            tag=":$CI_COMMIT_REF_SLUG"
            echo "Running on branch '$CI_COMMIT_BRANCH': tag = $tag"
          fi
        - docker build -t "$CI_REGISTRY_IMAGE${tag}" -t "$DOCKER_HUB_REGISTRY${tag}" .
        - docker push "$CI_REGISTRY_IMAGE${tag}"
        - docker push "$DOCKER_HUB_REGISTRY${tag}"

    rules:
    - if: $CI_COMMIT_BRANCH
      exists:
        - Dockerfile
